using System;
using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.Security.Permissions;
using System.Threading;
using System.Windows.Input;
using System.Xml.Serialization;
using Pokemon_Beep.Combat;
using Pokemon_Beep.Factory;
using Pokemon_Beep.Graphic;
using Pokemon_Beep.Player;
using Pokemon_Beep.Pokemon;

namespace Pokemon_Beep.Other
{
    class Testing
    {
        /// <summary>
        /// This class is used for testing. Will be removed when the game is done.
        /// </summary>
        private Thread music = new Thread(() => Utilities.startMusic(0));
        public void battleTest()
        {
            Protagonist protag = new Protagonist("James", 0);
            PokemonFactory factory = new PokemonFactory();
            PokemonInfo player = factory.getPokemon(2);
            PokemonInfo foe = factory.getPokemon(5);
            PocketMonster playerPkmn = new PocketMonster(2, 10);
            PocketMonster foePkmn = new PocketMonster(7, 10);

            protag.Pokemons.Add(playerPkmn);

            Battle battle = new Battle();

            Console.Clear();

            battle.startWildBattle(protag, foePkmn, 0);
            
        }
        public void battleGraphic()
        {
            //BattleBackground background = new BattleBackground();
            Console.SetWindowSize(152, 41);
            Console.SetBufferSize(152, 41);
            Utilities.changeBackgroundColor(50, 50, 50);
            Console.Clear();
            //Background
            //background.writeBackground(3);
            //Player's Pokemon
            writePlayerPokemon(8, 16);
            //Foe's Pokemon
            writeFoePokemon(100, 10);
            //UI
            writeUI(60, 32);
            //Text
            writeText("A wild Dunspace Appears !", 62, 33);


            void writePlayerPokemon(int x, int y)
            {
                int oldX = x;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 24, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 22, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 20, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 2, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 12, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 2, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;163;43m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 10, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 2, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;163;43m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 2, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 4, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;163;43m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 4, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 2, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 2, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;

                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;188;188;188m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;

                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;188;188;188m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;188;188;188m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;

                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;

                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;

                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;

                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;163;43m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;72;0;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;188;188;188m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;

                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;163;43m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 2, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;148;125;242m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;0;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;106;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 2, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 6, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 6, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 2, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 10, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;216;0m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 14, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;188;188;188m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 12, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.SetCursorPosition(x += 16, y);
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
                x = x + 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;11;9;10m██");
            }
            void writeFoePokemon(int x, int y)
            {
                int oldX = x;
                Console.SetCursorPosition(x += 34, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 32, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 32, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 30, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 18, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m████");
                x += 4;
                Console.SetCursorPosition(x += 6, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 16, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██████");
                x += 6;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x += 2, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m██████");
                x += 6;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 16, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██████");
                x += 6;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 10, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;180;180;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 6, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;186;218m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;238;189m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;186;218m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 4, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;238;189m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m████████");
                x += 8;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;238;189m██████");
                x += 6;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 2, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;238;189m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m████████");
                x += 8;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██████");
                x += 6;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 2, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m████████████");
                x += 12;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;180;180;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m██████");
                x += 6;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 2, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m████████");
                x += 8;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;186;218m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;255m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;180;180;197m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 2, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;255;115m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;186;218m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;238;189m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;186;218m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;238;189m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;238;189m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██████");
                x += 6;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;90;139m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;238;189m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m████");
                x += 4;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 6, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;90;139m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;82;82;82m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██████");
                x += 6;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;213;189;41m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 8, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;255;148;197m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m████████");
                x += 8;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                y++;
                x = oldX;
                Console.SetCursorPosition(x += 8, y);
                Console.Write("\x1b[38;2;0;0;0m██");
                x += 2;
                Console.SetCursorPosition(x, y);
                Console.Write("\x1b[38;2;0;0;0m██");
            }
            void writeUI(int x, int y)
            {
                Utilities.changeForegroundColor(255, 255, 255);
                Console.SetCursorPosition(x, y);
                Console.WriteLine("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█");
                y++;
                Console.SetCursorPosition(x, y);
                Console.WriteLine("█                                               █");
                y++;
                Console.SetCursorPosition(x, y);
                Console.WriteLine("█                                               █");
                y++;
                Console.SetCursorPosition(x, y);
                Console.WriteLine("█                                               █");
                y++;
                Console.SetCursorPosition(x, y);
                Console.WriteLine("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█");
                y++;
            }
            void writeText(string text, int x, int y)
            {
                Console.SetCursorPosition(x, y);
                Console.WriteLine(text);
            }
            
        }
        public void testAudio()
        {
            Console.CursorVisible = false;
            //BattleBackground background = new BattleBackground();
            Console.SetWindowSize(152, 41);
            Console.SetBufferSize(152, 41);
            Utilities.changeBackgroundColor(50, 50, 50);
            Console.Clear();
            //Background
            //background.writeBackground(3);
            //Player's Pokemon
            music.Start();
            Console.Beep(100, 1000);
            Console.ReadKey();
            Utilities.ChangeMusic(2);
            Console.ReadKey();
            Utilities.ChangeMusic(0,1);
        }
        public void testThread()
        {
            Thread music = new Thread(() => Utilities.startMusic(0));
            music.Start();
            Console.ReadKey();
        }
        public void cameraTest()
        {
            //Console.SetWindowSize(82, 30);
            //Console.SetBufferSize(82, 30);
            Console.SetWindowSize(152, 41);
            Console.SetBufferSize(152, 41);
            Console.CursorVisible = false;

            Utilities.changeBackgroundColor(5, 5, 5);         

            int posJX = 240;
            int posJY = 40;

            Console.SetCursorPosition(0, 0);
            Console.WriteLine(" ╔═══════════════════════════════════════════════════════════════════════════════╗");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ║                                                                               ║");
            Console.WriteLine(" ╚═══════════════════════════════════════════════════════════════════════════════╝");


            MapFactory mapFactory = new MapFactory();
            List<Map> maps = mapFactory.getMaps();
            Map currentMap = maps[0];

            bool asMoved = true;

            while (true)
            {              

                if (asMoved)
                {
                    currentMap.printMap(posJX, posJY);
                    Console.SetCursorPosition(41, 14);
                    Utilities.changeForegroundColor(255, 163, 255);
                    Console.WriteLine("■");
                }

                //Tick on va dire
                Thread.Sleep(50);

                if (Keyboard.IsKeyDown(Key.S))
                {
                    posJY += 1;

                    if(currentMap.hit(posJX, posJY))
                        posJY -= 1;
                    currentMap.wildPokemon(posJX, posJY);
                    asMoved = true;
                }
                else if (Keyboard.IsKeyDown(Key.A))
                {
                    posJX -= 2;

                    if (currentMap.hit(posJX, posJY))
                        posJX += 2;
                    currentMap.wildPokemon(posJX, posJY);
                    asMoved = true;
                }
                else if (Keyboard.IsKeyDown(Key.W))
                {
                    posJY -= 1;

                    if (currentMap.hit(posJX, posJY))
                        posJY += 1;
                    currentMap.wildPokemon(posJX, posJY);
                    asMoved = true;
                }
                else if (Keyboard.IsKeyDown(Key.D))
                {
                    posJX += 2;

                    if (currentMap.hit(posJX, posJY))
                        posJX -= 2;
                    currentMap.wildPokemon(posJX, posJY);
                    asMoved = true;
                }
                else
                {
                    asMoved = false;
                }
            }
         
        }
        public void item()
        {
            IDictionary<int, int> invItems = new Dictionary<int, int>();

            //Adding Item
            invItems.Add(1, 1);
            invItems.Add(3, 15);

            //Trying to add/remove some items
            invItems[3] += 10;
            invItems[1] -= 1;

            Console.WriteLine(invItems[1] + " Pokeball");
            Console.WriteLine(invItems[3] + " GreatBall");

            //Removing the item from the inventory

            invItems.Remove(3);



        }
        public void catchTest()
        {
            PocketMonster pkm = new PocketMonster((int)Enum.pokemon.Zigzagoon, 13);
            pkm.CurrentHP = pkm.HP / 2;
            Battle battle = new Battle();
            while (true)
            {
                Utilities.changeForegroundColor(255, 255, 255);
                Console.WriteLine("===============================");
                Console.WriteLine(pkm.Nickname + "  HP:" + pkm.CurrentHP + "/" +  pkm.HP);
                Console.WriteLine("===============================");
                int shakes = battle.shakes(pkm, 1);
                Utilities.changeForegroundColor(255, 216, 0);
                Console.WriteLine("The Human throws a Pokéball at the wild " + pkm.Nickname);
                Thread.Sleep(800);
                if(shakes != 0)
                {
                    for (int i = 0; i < shakes; i++)
                    {
                        if( i != 3 )
                            Console.Write(".");
                        Thread.Sleep(800);
                    }
                    if (shakes == 4)
                    {
                        Utilities.changeForegroundColor(76, 255, 0);
                        Console.Write("Gotcha !");
                    }                      
                    else
                    {
                        Utilities.changeForegroundColor(255, 0, 0);
                        Console.Write("The wild Pokémon got Free !");
                    }
                }
                else
                {
                    Utilities.changeForegroundColor(255, 0, 0);
                    Console.WriteLine("The wild Pokémon got Free !");
                }
                Console.ReadKey();
                Console.Clear();
            }
        }
    }
}
